api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "bundle-product"
type = "function"
uid = "aa360ad7-16ed-1f9e-9036-5de66f91cf8a2be6d5f3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
